package com.mapchina.map

expect class MapController() {
    fun addOverlay(regionId: String, boundary: String, style: OverlayStyle)
    fun removeOverlay(regionId: String)
    fun clearOverlays()
    fun removeOverlaysExcept(regionIds: Set<String>)
    fun addMarker(attractionId: String, name: String, lat: Double, lng: Double, visited: Boolean)
    fun addAttractionMarker(attractionId: String, name: String, lat: Double, lng: Double, imageUrl: String?, visited: Boolean)
    fun removeMarker(attractionId: String)
    fun clearMarkers()
    fun addPolyline(id: String, points: List<Pair<Double, Double>>, color: Long, width: Float)
    fun removePolyline(id: String)
    fun clearPolylines()
    fun addImageMarker(id: String, lat: Double, lng: Double, imagePath: String, count: Int)
    fun removeImageMarker(id: String)
    fun clearImageMarkers()
    fun setCamera(lat: Double, lng: Double, zoomLevel: Float, animated: Boolean)
    fun setOnRegionTapListener(listener: ((String) -> Unit)?)
    fun setOnMarkerTapListener(listener: ((String) -> Unit)?)
    fun setOnCameraZoomChangeListener(listener: ((Float) -> Unit)?)
    fun setOnCameraPositionListener(listener: ((Double, Double, Float) -> Unit)?)
    fun setOnMapReadyListener(listener: (() -> Unit)?)
    fun pulseOverlay(regionId: String)
    fun restorePulsedOverlay()
    fun dispose()
}
